# Generated by Django 2.2.19 on 2024-07-09 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Укажите автора', max_length=200, verbose_name='Автор')),
                ('description', models.TextField(blank=True, help_text='Укажите информацию об авторе', verbose_name='Об авторе')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='pictures/authors/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('author_name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(help_text='Укажите название категории', max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Укажите уникальный фрагмент URL-адреса категории', unique=True, verbose_name='Уникальный фрагмент URL-адреса категории')),
                ('description', models.TextField(blank=True, help_text='Здесь должно быть описание категории', verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('category_title',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(help_text='Укажите название песни', max_length=200, verbose_name='Название песни')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('description', models.TextField(blank=True, help_text='Укажите информацию о песни', verbose_name='Информация о песни')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='pictures/songs/', verbose_name='Изображение')),
                ('count_views', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров песни')),
                ('author', models.ForeignKey(blank=True, help_text='Выберите имя автора песни', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.Author', verbose_name='Автор песни')),
                ('categories', models.ManyToManyField(blank=True, help_text='Выберите категории песни', related_name='songs', to='songs.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'ordering': ('song_title',),
            },
        ),
        migrations.CreateModel(
            name='SongFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Загрузите файл песни', upload_to='songs/', verbose_name='Файл песни')),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'легкая версия'), ('medium', 'удобное переложение'), ('hard', 'для опытных музыкантов')], help_text='Выберите сложность', max_length=16, null=True, verbose_name='Сложность')),
                ('video', models.URLField(help_text='Укажите cсылку на видео', verbose_name='Ссылка на видео')),
                ('song', models.ForeignKey(help_text='Укажите песню', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.Song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='SongCountViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesId', models.CharField(db_index=True, max_length=150)),
                ('songId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('liked', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайкер')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Разместите здесь комментарий', verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='songs.Song', verbose_name='песня')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('-created',),
            },
        ),
    ]
