# Generated by Django 2.2.19 on 2024-07-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfile',
            name='song',
            field=models.ForeignKey(help_text='Укажите песню', on_delete=django.db.models.deletion.CASCADE, related_name='songfiles', to='songs.Song', verbose_name='Песня'),
        ),
        migrations.AlterField(
            model_name='songfile',
            name='video',
            field=models.URLField(blank=True, help_text='Укажите cсылку на видео', null=True, verbose_name='Ссылка на видео'),
        ),
    ]
