# Generated by Django 2.2.19 on 2023-06-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songcountviews',
            options={'verbose_name': 'Просмотр', 'verbose_name_plural': 'Количество просмотров'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Здесь должно быть описание категории', verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Укажите имя автора песни', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.Author', verbose_name='Автор песни'),
        ),
    ]
