# Generated by Django 2.2.19 on 2023-08-27 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(help_text='Укажите название файла', max_length=200, verbose_name='Название файла')),
                ('file', models.FileField(help_text='Загрузите файл песни', upload_to='songs/', verbose_name='Файл песни')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('file_title',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(help_text='Укажите название видео', max_length=200, verbose_name='Название видео')),
                ('link', models.URLField(help_text='Укажите cсылку на видео', verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('video_title',),
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('author_name',), 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_title',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('song_title',), 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.RemoveField(
            model_name='like',
            name='created',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='song',
            name='category',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_file',
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории песни', related_name='songs', to='songs.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, help_text='Укажите информацию о песни', verbose_name='Информация о песни'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, help_text='Укажите информацию об авторе', verbose_name='Об авторе'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Здесь должно быть описание категории', verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайкер'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Выберите имя автора песни', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='songs.Author', verbose_name='Автор песни'),
        ),
        migrations.AddField(
            model_name='song',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='Выберите файлы песни', to='songs.File', verbose_name='Файлы'),
        ),
        migrations.AddField(
            model_name='song',
            name='videos',
            field=models.ManyToManyField(blank=True, help_text='Выберите видео', to='songs.Video', verbose_name='Категории'),
        ),
    ]
