# Generated by Django 2.2.19 on 2023-09-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20230827_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], help_text='Выберите сложность', max_length=16, null=True, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='song',
            name='videos',
            field=models.ManyToManyField(blank=True, help_text='Выберите видео', to='songs.Video', verbose_name='Видео'),
        ),
    ]
