# Generated by Django 2.2.19 on 2023-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20230603_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='count_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков песни'),
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, help_text='Укажите информацию о песни', verbose_name='Информация о песни'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, help_text='Укажите информацию об авторе', verbose_name='Об авторе'),
        ),
    ]
