# Generated by Django 2.2.19 on 2023-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20230604_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songcountviews',
            name='songId',
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'song'), name='unique_favorites'),
        ),
        migrations.DeleteModel(
            name='SongCountViews',
        ),
    ]
