# Generated by Django 2.2.19 on 2023-09-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20230902_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='pictures/songs/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='pictures/authors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='file',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'легкая версия'), ('medium', 'удобное переложение'), ('hard', 'для опытных музыкантов')], help_text='Выберите сложность', max_length=16, null=True, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='video',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'легкая версия'), ('medium', 'удобное переложение'), ('hard', 'для опытных музыкантов')], help_text='Выберите сложность', max_length=16, null=True, verbose_name='Сложность'),
        ),
    ]
