# Generated by Django 2.2.19 on 2023-06-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_songcountviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songcountviews',
            old_name='postId',
            new_name='songId',
        ),
    ]
